#!/bin/bash
#2 new queues:
#
#adis_extended_q_adis
#
#route : adis_i -> power_queue_i -> adis
#
#adis_extended_q_power
#
#route : adis_i -> power_queue_i -> power_queue
#

#!! first make sure the home queue is priority above 100

#extended self
qmgr -c 'p q adis'|grep -v '^#'|sed s/Execution/Route/g|sed 's/adis/adis_in/g'
#add : 
echo 'set queue adis_in route_destinations = adis_i'
echo 'set queue adis_in route_destinations += power_queue_i'
echo 'set queue adis_in route_destinations += adis'


#i queue
qmgr -c 'p q adis'|grep -v '^#'|sed 's/adis/adis_i/g'
#add :
echo 'set queue adis_i queued_jobs_threshold = [o:PBS_ALL=0]'

#add extended power
qmgr -c 'p q adis'|grep -v '^#'|sed s/Execution/Route/g|sed 's/adis/adis_extended_q_power/g'
#add : 
echo 'set queue adis_in route_destinations = adis_i'
echo 'set queue adis_in route_destinations += power_queue_i'
echo 'set queue adis_in route_destinations += power_queue'


