#!/bin/bash -l
alias cp='cp'
/root/power5_pbspro_configs_git/scripts/qstat_report > /var/www/html/wordpress/queue_stats_source
sleep 5
/usr/local/bin/txt2html /var/www/html/wordpress/queue_stats_source > /var/www/html/wordpress/queue_stats.html
