#!/bin/bash
#2 new queues:
#
#adis_extended_q_adis
#
#route : adis_0q -> power_queue_0q -> adis
#
#adis_extended_q_power
#
#route : adis_0q -> power_queue_0q -> power_queue
#

#!! first make sure the home queue is priority above 100

#extended self
qmgr -c 'p q adis'|grep -v '^#'|sed s/Execution/Route/g|sed 's/adis/adis_in/g'
#add : 
echo 'set queue adis_in route_destinations = adis_0q'
echo 'set queue adis_in route_destinations += power_queue_0q'
echo 'set queue adis_in route_destinations += adis'


#adis_0q queue
qmgr -c 'p q adis'|grep -v '^#'|sed 's/adis/adis_0q/g'
#add :
echo 'set queue adis_0q max_queued_res.ncpus = [o:PBS_ALL=168]'
#then do power_0q1 -> adis power_0qa1 a 0 queue specific to adis_0q
#meaning that it contans all the nodes NOT in adis_0q


#add extended power
qmgr -c 'p q adis'|grep -v '^#'|sed s/Execution/Route/g|sed 's/adis/adis_out/g'
#add : 
echo 'set queue adis_in route_destinations = adis_0q'
echo 'set queue adis_in route_destinations += power_queue_0q'
echo 'set queue adis_in route_destinations += power_queue'


